
import './theme.config.css'
import '@radix-ui/themes/styles.css';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Theme, ThemePanel } from '@radix-ui/themes';
import { Footer, Navbar } from '@/components';

const inter = Inter({ subsets: ['latin'] ,
variable:'--font-inter'})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>

      <Theme appearance='light' accentColor="purple">
<Navbar/>
     


<main className='p-5'>
{children}
</main>
<Footer/>
{/* <ThemePanel/> */}
</Theme>
      </body>
    </html>
  )
}
